version: '3.6'

services:

  influx:
    image: library/influxdb:latest
    ports:
      - 8086:8086
      - 8083:8083

  chronograf:
    image: library/chronograf:latest
    ports:
      - 8888:8888
    links:
      - influx
    environment:
      INFLUXDB_URL: "http://influx:8086"

  telegraf:
    restart: always
    image: library/telegraf:1.3.2
    volumes:
      - ./docker/telegraf:/etc/telegraf
    ports:
      - 8125:8125/udp
      - 8094:8094/tcp
    depends_on:
      - influx

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana:/etc/grafana
    depends_on:
      - influx

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: "app"
    volumes:
      - ./docker/mongo/data:/docker-entrypoint-initdb.d

  express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
